//created on: Jun 4, 2018
package firstGroup

//list any import classes here.
import drools.model.Chart;
import drools.model.Examination;
import drools.model.Symptom;
import drools.model.Disease;
import java.util.Date;

//declare any global variables here

rule "Prehlada"
	salience $count.intValue()*100/5
	activation-group "x"
	agenda-group "diagnose"
    when
        $chart: Chart($exams: examinations)
        $exam: Examination(disease == null, $symptoms: symptoms) from $exams
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Curenje iz nosa" || name=="Bol u grlu" || name=="Glavobolja"
        		|| name=="Kijanje" || name=="Kasalj") from $symptoms,
        	count(1)
        )
    then
    	Disease d = new Disease(0, "Prehlada", null);
    	$exam.setDisease(d);
    	update($chart);
        System.out.println("U pitanju je prehlada");

end


rule "Groznica"
	salience $count.intValue()*100/7
	activation-group "x"
	agenda-group "diagnose"
	when
		$chart: Chart($exams: examinations)
        $exam: Examination(disease == null, $symptoms: symptoms) from $exams
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Curenje iz nosa" || name=="Bol u grlu" || name=="Glavobolja"
        		|| name=="Kijanje" || name=="Kasalj" || name=="Drhtavica" 
        		|| name=="Temperatura veca od 38") from $symptoms,
        	count(1)
        )
	then
		Disease d = new Disease(1, "Groznica", null);
    	$exam.setDisease(d);
    	update($chart);
		System.out.println("U pitanju je groznica");
end

rule "Upala krajnika"
    salience $count.intValue()*100/8
    activation-group "x"
    agenda-group "diagnose"
    when
        $chart: Chart($exams: examinations)
        $exam: Examination(disease == null, $symptoms: symptoms) from $exams
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Bol u grlu" || name=="Bol koji se siri do usiju" || name=="Glavobolja" || 
        		name=="Temperatura od 40 do 41" || name=="Drhtavica" || name=="Gubitak apetita" ||
        		name=="Umor" || name=="Zuti sekret iz nosa") from $symptoms,
        	count(1)
        )
    then
        Disease d = new Disease(2, "Upala krajnika", null);
    	$exam.setDisease(d);
    	update($chart);
		System.out.println("U pitanju je upala krajnika");

end

rule "Sinusna infekcija"
	salience $count.intValue()*100/7
	activation-group "x"
	agenda-group "diagnose"
	when
		$chart: Chart($exams: examinations)
        $exam: Examination(disease == null, $symptoms: symptoms) from $exams
        $count: Number(intValue >= 3) from accumulate (
        	Symptom(name=="Oticanje oko ociju" || name=="Glavobolja" || name=="Zuti sekret iz nosa" 
        		|| name=="Bol u grlu" || name=="Temperatura veca od 38" || name=="Kasalj") from $symptoms,
        	count(1)
        )
        $specCount: Number(intValue >= 0) from accumulate (
        	Examination(
        		this != $exam,
        		this meets[60d] $exam,
        		$disease: disease
        	) and
        	Disease( name == "Prehlada" || name == "Groznica"),
        	count(1)
        )
        eval($count.intValue() + $specCount.intValue() >= 4)
	then
		Disease d = new Disease(2, "Sinusna infekcija", null);
    	$exam.setDisease(d);
    	update($chart);
		System.out.println("U pitanju je sinusna infekcija");
end

function boolean checkLastColdFever(Chart chart, Examination exam) {
	for(Examination m: chart.getExaminations()) {
		if(m.getDisease()!= null && (m.getDisease().getName().equals("Prehlada") || m.getDisease().getName().equals("Groznica"))){
			if((exam.getDate().getTime() - m.getDate().getTime()) / (60*60*24*1000) < 60)
				return true;
		}
	}
	
	return false;
}