//created on: Jun 4, 2018
package firstGroup

//list any import classes here.
import drools.model.Chart;
import drools.model.Examination;
import drools.model.Symptom;
import drools.model.Disease;
import java.util.Date;

//declare any global variables here

rule "Prehlada"
	salience $count.intValue()*10000/5
	activation-group "x"
	agenda-group "diagnose"
    when
        Chart()
        $exam: Examination($symptoms: symptoms)
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Curenje iz nosa" || name=="Bol u grlu" || name=="Glavobolja"
        		|| name=="Kijanje" || name=="Kasalj") from $symptoms,
        	count(1)
        )
    then
    	System.out.println("Salience je: "+$count.intValue()*10000/5);
    	Disease d = new Disease(0, "Prehlada" );
    	insert(d);
        System.out.println("U pitanju je prehlada");

end


rule "Groznica"
	salience $count.intValue()*10000/7
	activation-group "x"
	agenda-group "diagnose"
	when
		Chart()
        $exam: Examination($symptoms: symptoms)
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Curenje iz nosa" || name=="Bol u grlu" || name=="Glavobolja"
        		|| name=="Kijanje" || name=="Kasalj" || name=="Drhtavica" 
        		|| name=="Temperatura veca od 38") from $symptoms,
        	count(1)
        )
	then
		System.out.println("Salience je "+$count.intValue()*10000/7);
		Disease d = new Disease(1, "Groznica" );
    	insert(d);
		System.out.println("U pitanju je groznica");
end

rule "Upala krajnika"
    salience ($count.intValue()*10000/8)
    activation-group "x"
    agenda-group "diagnose"
    when
        Chart()
        $exam: Examination($symptoms: symptoms)
        $count: Number(intValue >= 4) from accumulate (
        	Symptom(name=="Bol u grlu" || name=="Bol koji se siri do usiju" || name=="Glavobolja" || 
        		name=="Temperatura od 40 do 41" || name=="Drhtavica" || name=="Gubitak apetita" ||
        		name=="Umor" || name=="Zuti sekret iz nosa") from $symptoms,
        	count(1)
        )
    then
    	System.out.println("Salience je "+($count.intValue()*10000/8));
        Disease d = new Disease(2, "Upala krajnika" );
    	insert(d);
		System.out.println("U pitanju je upala krajnika");

end

rule "Sinusna infekcija"
	salience $count.intValue()*10000/7 + $sC.intValue()*10000/7
	activation-group "x"
	agenda-group "diagnose"
	when
		Chart($exams: examinations)
        $exam: Examination($symptoms: symptoms)
        $count: Number(intValue >= 3) from accumulate (
        	Symptom(name=="Oticanje oko ociju" || name=="Glavobolja" || name=="Zuti sekret iz nosa" 
        		|| name=="Bol u grlu" || name=="Temperatura veca od 38" || name=="Kasalj") from $symptoms,
        	count(1)
        )
        $specCount: Number(intValue >= 0) from accumulate (
        	Examination(
        		this != $exam,
        		this meets[60d] $exam,
        		$disease: disease
        	) from $exams and
        	Disease( name == "Prehlada" || name == "Groznica"),
        	count(1)
        )
        $sC: Number(intValue >= 0) from accumulate (
        	Number() from $specCount,
        	count(1)
        )
        eval(($count.intValue() + $sC.intValue()) >= 4)
	then
		System.out.println("Salience je "+($count.intValue()*10000/7 + $specCount.intValue()*10000/7) +" (spec count je "+$specCount.intValue()+")");
		Disease d = new Disease(3, "Sinusna infekcija");
    	insert(d);
		System.out.println("U pitanju je sinusna infekcija");
end