//created on: Jun 6, 2018
package allergies

//list any import classes here.



//declare any global variables here

import drools.model.Chart;
import drools.model.Examination;
import drools.model.Patient;
import drools.model.Allergen;
import drools.model.Prescription;
import drools.model.Drug;
import drools.model.Ingredient;

rule "Drug allergy"
	agenda-group "allergy-warning"
    when
        $chart: Chart($exams: examinations, $pat: patient)
        $p: Patient($allergies: allergens) from $pat
        $exam: Examination($prescription: prescription, disease!=null) from $exams
        $pp: Prescription($drug: drug) from $prescription
        $dr: Drug($drName: name) from $drug
    	$allergyCount: Number(intValue > 0) from accumulate (
    		Allergen(name == $drName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat + " ima alergiju na "+$dr.getName());
end

rule "Ingredient allergy"
	agenda-group "allergy-warning"
    when
        $chart: Chart($exams: examinations, $pat: patient)
        Patient($allergies: allergens) from $pat
        $exam: Examination($prescription: prescription, disease!=null) from $exams
        Prescription($drug: drug) from $prescription
        Drug($drName: name, $ingredients: ingredients) from $drug
        $in: Ingredient($inName: name) from $ingredients
    	$allergyCount: Number(intValue > 0) from accumulate (
    		Allergen(name == $inName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat + " ima alergiju na "+$in.getName());
end