//created on: Jun 6, 2018
package allergies

//list any import classes here.



//declare any global variables here

import drools.model.Chart;
import drools.model.Examination;
import drools.model.Patient;
import drools.model.Allergy;
import drools.model.Prescription;
import drools.model.Drug;
import drools.model.Ingredient;
import java.util.List;

global List<Allergy> allergyCont;

rule "Drug allergy"
	agenda-group "allergy-warning"
    when
        $pat: Patient($allergies: allergens)
        $dr: Drug($drName: name)
    	$allergyCount: Number(intValue > 0) from accumulate (
    		Allergy(name == $drName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat.getFirstName() + " ima alergiju na "+$dr.getName());
        allergyCont.add(new Allergy(0, $dr.getName()));
end

rule "Ingredient allergy"
	agenda-group "allergy-warning"
    when
        $pat: Patient($allergies: allergens)
        Drug($drName: name, $ingredients: ingredients)
        $in: Ingredient($inName: name) from $ingredients
    	$allergyCount: Number(intValue > 0) from accumulate (
    		$aa: Allergy(name == $inName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat.getFirstName() + " ima alergiju na "+$in.getName());
        allergyCont.add(new Allergy(0, $in.getName()));
end