//created on: Jun 6, 2018
package allergies

//list any import classes here.



//declare any global variables here

import drools.model.Chart;
import drools.model.Examination;
import drools.model.Patient;
import drools.model.Allergy;
import drools.model.Prescription;
import drools.model.Drug;
import drools.model.Ingredient;

rule "Drug allergy"
	agenda-group "allergy-warning"
    when
        $pat: Patient($allergies: allergens)
        Examination($pp: prescription)
        Prescription($drug: drug) from $pp
        $dr: Drug($drName: name) from $drug
    	$allergyCount: Number(intValue > 0) from accumulate (
    		Allergy(name == $drName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat + " ima alergiju na "+$dr.getName());
        insert(new Allergy(0, $dr.getName()));
end

rule "Ingredient allergy"
	agenda-group "allergy-warning"
    when
        $pat: Patient($allergies: allergens)
        Examination($pp: prescription)
        Prescription($drug: drug) from $pp
        Drug($drName: name, $ingredients: ingredients) from $drug
        $in: Ingredient($inName: name) from $ingredients
    	$allergyCount: Number(intValue > 0) from accumulate (
    		$aa: Allergy(name == $inName) from $allergies,
    		count(1)
    	)
    then
        System.out.println($pat + " ima alergiju na "+$in.getName());
        insert(new Allergy(0, $in.getName()));
end