//created on: Jun 4, 2018
package secondGroup

//list any import classes here.
import drools.model.Chart;
import drools.model.Examination;
import drools.model.Symptom;
import drools.model.Disease;
import java.util.Date;
import java.util.List;


//declare any global variables here
global List<Disease> diseaseCont;

rule "Hipertenzija"
	agenda-group "diagnose"
	salience $cc.intValue()*1000
	//activation-group "x"
    when
    	Chart($exams: examinations)
    	$exam: Examination()
        $cc: Number(intValue >= 10) from accumulate (
        	$exam1: Examination(
        		this != $exam,
        		this meets[180d] $exam,
        		$symptoms: symptoms
        	) from $exams and
        	Symptom(name == "Povisen krvni pritisak") from $symptoms,
        	count(1)
        )
    then
    	System.out.println("Salience je "+$cc.intValue()*1000);
       	diseaseCont.add(new Disease(6, "Hipertenzija"));
		System.out.println("U pitanju je hipertenzija ");
end

rule "Dijabetes"
    agenda-group "diagnose"
    //activation-group "x"
    salience $count.intValue()*10000/4
    when
       	Chart()
    	Examination($symptoms: symptoms)
    	$count: Number(intValue == 4) from accumulate (
    		Symptom(name=="Cesto uriniranje" || name=="Gubitak telesne tezine"
    			|| name=="Zamor" || name=="Mucnina i povracanje") from $symptoms,
    		count(1)
    	)
    then
    	System.out.println("Salience je "+$count.intValue()*10000/4);
        diseaseCont.add(new Disease(7, "Dijabetes"));
		System.out.println("U pitanju je dijabetes");

end
