insert into symptom (id, name) values (1, "Glavobolja");
insert into symptom (id, name) values (2, "Curenje iz nosa");
insert into symptom (id, name) values (3, "Bol u grlu");
insert into symptom (id, name) values (4, "Kijanje");
insert into symptom (id, name) values (5, "Kasalj");
insert into symptom (id, name) values (6, "Drhtavica");
insert into symptom (id, name) values (7, "Temperatura veca od 38");
insert into symptom (id, name) values (8, "Bol koji se siri do usiju");
insert into symptom (id, name) values (9, "Temperatura od 40 do 41");
insert into symptom (id, name) values (10, "Umor");
insert into symptom (id, name) values (11, "Zuti sekret iz nosa");
insert into symptom (id, name) values (12, "Gubitak apetita");
insert into symptom (id, name) values (13, "Oticanje oko ociju");
insert into symptom (id, name) values (14, "Povisen krvni pritisak");
insert into symptom (id, name) values (15, "Cesto uriniranje");
insert into symptom (id, name) values (16, "Gubitak telesne tezine");
insert into symptom (id, name) values (17, "Zamor");
insert into symptom (id, name) values (18, "Mucnina i povracanje");
insert into symptom (id, name) values (19, "Otoci nogu i zglobova");
insert into symptom (id, name) values (20, "Nocturia");
insert into symptom (id, name) values (21, "Gusenje");
insert into symptom (id, name) values (22, "Bol u grudima");
insert into symptom (id, name) values (23, "Dijareja");
insert into symptom (id, name) values (24, "Oporavlja se od operacije");